# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b877d2a8390b5f92fe3ad25ce2262ec56286a8b852316553621f8c2730de2caa7e4b8854396c9ebe2e392dde854078a662bfdfc9a32f41d6796bfbb2a2ca971

test:
  secret_key_base: 2946e132c6847717e32f77955ba3a8c1ddb6d319f8f205ccc64f9c4d71bef95b07e923d3983711769584092434ab44bc50b751307a343dc077553c5ec6b4c0de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
